### ISSUE TITLE
Option, no need to disolder the module

### ISSUE THREAD

**Issue by chaveiro** [krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota#10]
I've been programing the modules without disordering.
Just remove from the LCD board from the power module, connect the programing pins, gnd and 3.3V, ensure a good power supply able to supply 200mA or more, and that is enough.
With the lcd module floating on the air the tuya mcu is usually stuck in reset so it does not interfere with the programming.

![image](https://user-images.githubusercontent.com/4527135/124747294-b04dd780-df19-11eb-962f-7e01ce873563.png)

**Comment by krikk** [comment]
as fare as i remember, i did try this first also, but did not work for me (see picture: https://raw.githubusercontent.com/krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota/main/pictures/espboard_front.jpg)

**Comment by chaveiro** [comment]
See the photo i update above. It works for me :)
BTW: On your photo there seems to be a solder link between TX and RX?

**Comment by krikk** [comment]
> BTW: On your photo there seems to be a solder link between TX and RX?

doh, could be a solder problem, right, i updated my readme and linked to your image...
