### ISSUE TITLE
Option, Save and Restore original firmware

### ISSUE THREAD

**Issue by chaveiro** [krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota#11]
Save bakup of original firmware: 
python esptool.py --port COM15 --baud 115200 read_flash 0x00000 0x100000 backup1.img

Restore original firmware:
python esptool.py --port COM15 --baud 234000 write_flash -fm qio -fs 1MB 0x00000 backup1.img

(Adjust the port)

**Comment by krikk** [comment]
integrated in main readme, thx
