### ISSUE TITLE
cannot flash the meter

### ISSUE THREAD

**Issue by luciandf** [krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota#18]
Hello I have just purchased this meter and wanted to flash tasmota to it so I can integrate it into homeassistant. However, whatever I try I cannot get it to flash.

I am using windows 11 and followed all the guides to the letter. But no matter what I do is I get a timeout in the tasmotizer like so:

![image](https://user-images.githubusercontent.com/48201912/161450532-787824cb-86ac-46a8-be90-af5fc9a01e70.png)

What is it that I am doing wrong?

I tried to pinout from here: https://user-images.githubusercontent.com/4527135/124747294-b04dd780-df19-11eb-962f-7e01ce873563.png

I have a feeling that there is something missing and I can't figure it out.

Cheers

**Comment by davoau** [comment]
Hi, I was getting a similar error, and it was either not enough power getting to the ESP, or the USB TTL programmer I was using. I tried two others before I used a CP2102 which worked.

Check out my post below as there is a link to the programmer that worked for me.
https://github.com/krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota/issues/15

**Comment by luciandf** [comment]
thank you for your suggestion! I was trying with this USB TTL programmer:
![IMG_20220404_081907](https://user-images.githubusercontent.com/48201912/161479172-2acb792e-aa2d-4a09-a56a-137abd9924c1.jpg)

I have no idea if it is the right one. I have used it in the past to program an ESP12F and I thought it would work here too. I have ordered the one you mentioned and hopefully I can get it to work. I see that you designed you own jig on a 3d printer. Are you also producing these now? Can I buy one?

Can you confirm that the wiring from the link in my original post is correct? Are you using different pins with your jig?

Thank you!

**Comment by davoau** [comment]
Hi,
The 2 ttl programmers I tried that didn't work I had also used in the past to program sonoff switches which use ESP8266 without a problems. So I am not sure why they didn't work on this energy meter. I was lucky I already had the CP2102 to try and it worked. I purchased a set of 3 different programmers on aliexpress, which had a CP2102, CH340G and PL2303, and of course after a lot of frustration of it not programming it was the CP2102 that I tried last which worked. 

The wiring in the original info is correct. Follow this guide as it is a bit clearer:
https://github.com/krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota/issues/13

I didn't design the jigs, I found the design already on thingyverse.com and printed it out. Links are in my post for the files. I am in Australia, and am guessing you are in USA, so it would be quicker for you to find someone with a 3D printer to print one out. 
You can solder the cables directly to the pogo pins if you don't have the test probes already.

It was very frustrating to get the first one programmed, with lots of trial and error, but once I did the first one and knew what I was doing it took a minute to do the other 2. I have ordered another 3 off aliexpress in their sale that started beginning to this month as I want to monitor individual circuits in my house and am using one to turn on hotwater cylinder when solar is producing enough power so I don't suck any power out of grid.

Hope this helps.

**Comment by luciandf** [comment]
Thank you for your detailed response! I have just received my order for two new programmers with the CP2102 chip (see below):
![IMG_20220405_083512](https://user-images.githubusercontent.com/48201912/161685750-5515b7f5-8366-45f8-8a60-d6e2ecb993ce.jpg)

I will follow the wiring scheme you recommended and see what happens (I have tried it with the old programmer but it didn't work, but try try try again!).

I am from Romania so that's not better for postage either. I will try to get one printed out but if I am successful without I think I will skip the jig. I don't do this that often, only for small home automation projects. 

If I manage to integrate this meter I will get another one to monitor the air conditioning for the summer and the power tools in the yard!

I will report back the results!

Cheers!

**Comment by luciandf** [comment]
it worked like a charm! thank you very much for your help and patience!

**Comment by davoau** [comment]
Good to hear it worked for you. Thanks for the update.
I have been reading up about the ttl programmers and people have said the CP2102 was designed by silicon labs, and has better driver support for windows, so is more reliable compared to the chinese designed chips like the CH340. However under linux it maybe makes not difference.

**Comment by luciandf** [comment]
I was under linux! So I guess the CH340 isn't working right anywhere...

*Lucian*

*Website: **http://lucianfilip.wordpress.com
<http://lucianfilip.wordpress.com/>*
