### ISSUE TITLE
Tasmota: missing frequency and reverse power flow

### ISSUE THREAD

**Issue by g6094199** [krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota#19]
i dont know if this is a general tasmota or setting thing or simply gets not pushed.

but the device can show the frequency on the display and it would be nice to have it in tasmota, too!
also i see its a 2 way power meter so it would also nice to have to see the forward and reverse power flow. this is very handy eg. when use the meter for a solar planel inverter(s)  where the power flows forward in the nighttime and reverse on  daytime. or vice versa when used on solar powered battey inverters or on USVs on power outages.

can we get this working?

sash

**Comment by krikk** [comment]
nope, not possible, the tuya interface does not expose everything which the device can measure (and display on the lcd) ...perhaps  other hardware revisions expose more, but mine does not... you can test yourself, see tasmota docs: https://tasmota.github.io/docs/TuyaMCU/

**Comment by g6094199** [comment]
sems ESPHome is counting +/- kwh, though.

https://www.esphome-devices.com/devices/hiking-dds238-2-wifi/

![Bildschirmfoto vom 2022-05-14 11-42-46](https://user-images.githubusercontent.com/37833326/168420415-765da371-75e4-4459-a0e1-bcf5874227f9.png)

**Comment by ayasystems** [comment]
@g6094199 i will try, seems like 9 is sending data

![image](https://user-images.githubusercontent.com/7864168/168464030-d33afe05-f660-4719-a19d-254539bae28b.png)

**Comment by ayasystems** [comment]
I'm sorry, i was wrong.... My meter is not sending data over DpId 9

![image](https://user-images.githubusercontent.com/7864168/168464247-970a1e37-fc22-4de1-a867-50ea1d99f13a.png)

**Comment by g6094199** [comment]
hmmm...i see:

>  05:15.619 MQT: tele/tasmota_C64D61/RESULT = {"TuyaReceived" {"Data":"55AA03070008090200040000000020","Cmnd":7,"CmndData":"0902000400000000","DpType2Id9":0,"9":{"DpId":9,"DpIdType":2,"DpIdData":"00000000"}}}

on my device.

**Comment by ayasystems** [comment]
I think that dpid is not reverse energy, It is always 0000.
I put power line inverted and show A and w as positive value, I think that both directions are registered as positive energy

**Comment by g6094199** [comment]
seems the tuya mcu does something like absolute value of both power flows and sums em up, so the result is always positive and increasing.
