### ISSUE TITLE
It's working ?

### ISSUE THREAD

**Issue by lupumihai** [krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota#2]
Hello, 

I see that you are using TASMOTA configuration for Tuya connect. Tuya software is written on the ESP module and not in the Power meter IC,  into the one you just flashed!

Can you confirm if this setup is working? 
... does TASMOTA support direct communication with G80F923?

**Comment by lupumihai** [comment]
So, It's working --> this answers my question.

Now seems that I have a problem with reading or calibration, any further idea?

![image](https://user-images.githubusercontent.com/54285239/106499227-0204b880-64c9-11eb-97f0-39aa227afddb.png)

**Comment by krikk** [comment]
yes my setup is working... perhaps you have other hardware??
