### ISSUE TITLE
disconnected from wifi how to reconnect?

### ISSUE THREAD

**Issue by luciandf** [krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota#21]
Hello,

I have followed the guide and all was well with the meter so I went ahead and installed it to measure the power for the entire house. Two days after I installed it I lost contact with it (I was monitoring it through homeassistant integration). I still have power in the house but I just cant reconnect it to wifi.

What should I do? I have read that normally you would do the 6 on off cycles and get back to the wifi connection settings or something but this is not possible becuase I would destroy stuff in the house buy doing 6 fast on off cycles.

Is there something I can do to get it back online?

Upon inspection of the network, it appears as one of the clients in the router list but I cannot ping it!

**Comment by davoau** [comment]
Hi, I had a similar problem - was disconnecting, reconnecting, and sometimes would not connect for hours. I flashed with latest version of tasmota, which helped a bit, but then moved it over in the switch board to put some distance between it an another wifi meter and haven't had a problem since.
