### ISSUE TITLE
Missing frequency Hz and reverse kWh read out

### ISSUE THREAD

**Issue by Dark-Noir** [krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota#22]
Hey,

is it possible to add the missing read outs for frequency in Hz and reverse kWh?

I have not enough experience with TuyaMCU, but maybe there is a fnId/dpId which deliver these read outs?

The documentation at https://tasmota.github.io/docs/TuyaMCU/#fnid seems to be incomplete (as noted), the fnID 37 is also missing there.

A solution would be nice 🙂

**Comment by krikk** [comment]
nope, there are no fnId/dpId which contains the data, it's simply not there.
