### ISSUE TITLE
DDS238-2 Zigbee Tuya - flashing

### ISSUE THREAD

**Issue by jproveta** [krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota#28]
I have the Zigbee Tuya version instead of WiFi, can I also do the same, change the firmware to the Tasmota?

Thanks.

**Comment by krikk** [comment]
don't think so, open it an look if you find the following chip:

https://tasmota.github.io/docs/devices/TYWE3S/

https://raw.githubusercontent.com/krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota/main/pictures/displayboard_back_with_espboard.jpg

i suspect that you can't find it in the zigbee version...

**Comment by jproveta** [comment]
> don't think so, open it an look if you find the following chip:
> 
> https://tasmota.github.io/docs/devices/TYWE3S/
> 
> https://raw.githubusercontent.com/krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota/main/pictures/displayboard_back_with_espboard.jpg
> 
> i suspect that you can't find it in the zigbee version...

Thanks, I'il see.

**Comment by jproveta** [comment]
No :( the one I have is in the picture. ZS3L
![IMG_3433](https://user-images.githubusercontent.com/9778385/226409195-d2249607-c252-45f3-827e-9a12fb18356c.png)

**Comment by krikk** [comment]
seems to be this [chip](https://developer.tuya.com/en/docs/iot/zs3l?id=K97r37j19f496): 
...and according to the datasheet it seems to have nearly the same pin-out than the TYWE3S, so it seems that they only changed the "interface" chip

**Comment by jproveta** [comment]
> seems to be this [chip](https://developer.tuya.com/en/docs/iot/zs3l?id=K97r37j19f496): ...and according to the datasheet it seems to have nearly the same pin-out than the TYWE3S, so it seems that they only changed the "interface" chip

Thank you.
