### ISSUE TITLE
Not switching with Tasmota

### ISSUE THREAD

**Issue by geeneo** [krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota#3]
I have the firmware flashed with Tasmota 9.2.0.  Followed the procedures Hiking DDS238-2 WIFI Module
Tasmota.  Seems the relay is not switching.

**Comment by martinportmann** [comment]
I had the same problem.
Go to Configuration / Configure Module / Module type.
Make sure that it says: Tuya MCU (54)

**Comment by krikk** [comment]
seems to me, like you did not apply the template... should look like this: https://github.com/krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota/raw/main/pictures/tasmota_module_config.png

just updated the readme...

**Comment by geeneo** [comment]
I did apply the template and not working.
