### ISSUE TITLE
Chipset WR3 instead of TYWE3S, unable to flash

### ISSUE THREAD

**Issue by radoprajitno** [krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota#30]
Hi.
I've recently bought the hiking DDS238-2-WIFI.
Straight open it up, trying the flashing without the soldering, 
But it didn't succeeded.

I've just realized, my Hiking-DDS238-2 comes with the WR3 Chip instead of the TYWE3S.
[https://imgur.com/a/J4shu8A](https://imgur.com/a/J4shu8A)

Is anyone here succeeded flashing that chip?

**Comment by krikk** [comment]
thanks for the info, sorry to hear that, but i don't think that will work with the new chip
datasheet of the chip: https://developer.tuya.com/en/docs/iot/wr3-module-datasheet?id=K9g3ainzbj9z1
