### ISSUE TITLE
Instructions broken - Latest Tasmota include some additional support

### ISSUE THREAD

**Issue by chaveiro** [krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota#4]
Just to advice that on latest Tasmota dev brach there is native support for DpId=101 data type.

Use this instead:
Backlog TuyaMCU 33,20; TuyaMCU 32,18; TuyaMCU 31,19;  TuyaMCU 37,101;
Backlog SetOption72 1; VoltRes 1; WattRes 1;

Also rule 2 is not needed as energy total will be available on ENERGY message.

Additionally see https://github.com/arendst/Tasmota/discussions/11837 requesting native support for this DDS238-2 WIFI devices all together.

**Comment by krikk** [comment]
> Just to advice that on latest Tasmota dev brach there is native support for DpId=101 data type.

only in dev branch or starting with which release version this is included?

**Comment by chaveiro** [comment]
To be safe, from 9.4.0.2 version.

**Comment by krikk** [comment]
are you sure this is working in the release version of 9.5.0?? i see no change in the energy message..

**Comment by chaveiro** [comment]
I'm sure that TuyaReceived#DpType2Id101 is now supported by the driver natively and 9.5.x brings some bug fixing to high power consumption schenarios that were overflowing some variables with unpredictable resulta.

**Comment by krikk** [comment]
you are right, forgot to enable SetOption72 1, now it is working as expected in 9.5.0 thx for the hint

**Comment by krikk** [comment]
updated my instructions...
