### ISSUE TITLE
Other datatypes ?

### ISSUE THREAD

**Issue by chaveiro** [krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota#5]
I wonder if the line frequency is available from the TuyaMCU itself.
How about dpId=9, what does it mean?

**Comment by chaveiro** [comment]
Answering myself, dpId=9 seem to be a timer to toggle the device relay.
Set it to any value and it starts counting down. 
By the time it reaches 0 the relay toggles state.

**Comment by krikk** [comment]
nice finding about dpId=9...

**Comment by krikk** [comment]
integrated this info into the main readme...
