### ISSUE TITLE
No issue only question

### ISSUE THREAD

**Issue by testpaul999** [krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota#6]
Hi,

Is it possible that you will sell one flashed device?
My knowledge with soldering are not so fine for this.

Regards

**Comment by krikk** [comment]
sorry, no time for such deals...

**Comment by testpaul999** [comment]
Schade… aber ok.

Viele Grüße

Jens-Uwe Franz

Am 28.04.2021 um 13:41 schrieb krikk ***@***.***>:

﻿

sorry, no time for such deals...
