### ISSUE TITLE
6 pins connector pinout (question)

### ISSUE THREAD

**Issue by hallard** [krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota#7]
Hi @krikk 
Very nice job, I ordered some to do some testing, I got some ideas to deal with that piece of hardware.

Would you mind (if ou know) tell me on the 6 pins connector from ESP board to main board how are wired the 2 pins in the middle. I think it should be GPIO14 and GPIO16 but I would like to know (I don't have hardware yet) how it's wired.

6 pin connector is as follow (tell me if I'm wrong) :

- Pin 1 is 3.3V
- Pin 2 is GND
- Pin 3 is ?
- Pin 4 is ?
- Pin 5 is RXD (RX Data from ESP or from main board? (I guess from ESP)
- Pin 6 is TXD (TX Data from ESP or from main board? (I guess from ESP)

which of pin 3 and 4 are LED (inverted) or Button ? Is button is active Low or High when idle?

Thank you very much for your help

**Comment by krikk** [comment]
sorry can't answer that, i have my only unit in productiv use, so can't test this, and don't remember how the connections where exactly, this github page is my memory :) sorry

**Comment by hallard** [comment]
For those interested order is 

- Pin 1 is 3.3V
- Pin 2 is GND
- Pin 3 is Key (4.7K pullup)
- Pin 4 is Led
- Pin 5 is RXD 
- Pin 6 is TXD
