### ISSUE TITLE
High level overview if what is achieved and what is possible using thins mod

### ISSUE THREAD

**Issue by spmp** [krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota#8]
Good day @krikk, 
 As a total newb to this world could you please include a high level of what can be achieved by this mod and what you are achieving please?
I pretty excited to see that this readily available device from AliExpress has an open source firmware that allows us to play 8)
I am looking to modify to include data logging to internal memory which can then be downloaded later. Do you know if this is possible with the Tasmota FW?

Sorry if this is the wrong place to ask - only just dipped my toes in 8)

Cheers,
Jasper

**Comment by krikk** [comment]
the original firmware is not open source...

your idea would be possible with tasmoa, but forget ist because of 2 problems:
- too much writes on internal flash memory, would destroy it on long run
- tasmota source is huge, if you have no knowledge, you really have a LOT to learn :)
