### ISSUE TITLE
EnergyToday EnergyTotal Problem

### ISSUE THREAD

**Issue by tnedev** [krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota#9]
Thank you very much for this guide!

I've got an issue. On restart, the daily and total energy get very high values from somewhere. I used the Tasmota energyreset to zero them out, but when I restart the device, they get overwritten with ~5000 KWh or so.

The voltage, power and current energy seems about right, it's just on restart that the total energy gets a bad value.

**Comment by krikk** [comment]
which version of tasmota are you using?

**Comment by tnedev** [comment]
I was first trying with 9.4.0, but there was a problem with the template. 
So instead I think I switched to 9.2.0 and it works besides the energy values after restart.

**Comment by krikk** [comment]
i use 9.4.0 for myself with this template:

`{"NAME":"Hiking DDS238-2 WIFI","GPIO":[0,2272,0,2304,0,0,0,0,0,0,320,0,32,0],"FLAG":0,"BASE":54}`

and i do not have such issues...

**Comment by krikk** [comment]
this was an issue with some of the "older" versions if i remember it correctly...

**Comment by tnedev** [comment]
I think the template is running fine. The problem is just on restart it gets a bad value for Today's KWh from somewhere. I copied your rules, but don't know what's the exact process and from where that bad values might come.

**Comment by krikk** [comment]
perhaps you can do a dump of your config in json format with https://github.com/tasmota/decode-config and send it to me, than i can compare your config with mine...

**Comment by chaveiro** [comment]
Use 9.5.x and see if the problem persists. Older versions have problems with large kwh values measurement.

**Comment by krikk** [comment]
solved in version >= 9.5
